"""Add processed_embedding to Snippet

Revision ID: 3f036435bcee
Revises: d03b63f3cd1f
Create Date: 2025-12-02 12:30:23.107229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f036435bcee'
down_revision: Union[str, Sequence[str], None] = 'd03b63f3cd1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('processed_embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snippets', 'processed_embedding')
    # ### end Alembic commands ###
