"""Add user stats

Revision ID: 44abdb04cca2
Revises: 7a2ea6d32ab5
Create Date: 2025-12-02 11:58:32.409954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44abdb04cca2'
down_revision: Union[str, Sequence[str], None] = '7a2ea6d32ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('overall_wpm', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('overall_accuracy', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('best_wpm', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('total_sessions', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_keystrokes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_keystrokes')
    op.drop_column('users', 'total_sessions')
    op.drop_column('users', 'best_wpm')
    op.drop_column('users', 'overall_accuracy')
    op.drop_column('users', 'overall_wpm')
    # ### end Alembic commands ###
