"""Add best_wpms to User and remove TelemetrySnippetRaw

Revision ID: 522fbdb2c09a
Revises: 15c3f8ba6dc1
Create Date: 2025-12-09 07:14:32.993613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '522fbdb2c09a'
down_revision: Union[str, Sequence[str], None] = '15c3f8ba6dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_snippet_raw_snippet_id'), table_name='telemetry_snippet_raw')
    op.drop_index(op.f('ix_telemetry_snippet_raw_user_id'), table_name='telemetry_snippet_raw')
    op.drop_table('telemetry_snippet_raw')
    op.add_column('users', sa.Column('best_wpms', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'best_wpms')
    op.create_table('telemetry_snippet_raw',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('snippet_id', sa.VARCHAR(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(), nullable=True),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('model_score', sa.FLOAT(), nullable=True),
    sa.Column('reward_estimate', sa.FLOAT(), nullable=True),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_snippet_raw_user_id'), 'telemetry_snippet_raw', ['user_id'], unique=False)
    op.create_index(op.f('ix_telemetry_snippet_raw_snippet_id'), 'telemetry_snippet_raw', ['snippet_id'], unique=False)
    # ### end Alembic commands ###
