"""initial schema rebuild

Revision ID: 7a2ea6d32ab5
Revises: 
Create Date: 2025-12-01 05:55:41.163761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2ea6d32ab5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('words', sa.JSON(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('normalized_features', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('difficulty_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_difficulty', 'snippets', ['difficulty_score'], unique=False)
    op.create_table('telemetry_snippet_raw',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('snippet_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('model_score', sa.Float(), nullable=True),
    sa.Column('reward_estimate', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_snippet_raw_snippet_id'), 'telemetry_snippet_raw', ['snippet_id'], unique=False)
    op.create_index(op.f('ix_telemetry_snippet_raw_user_id'), 'telemetry_snippet_raw', ['user_id'], unique=False)
    op.create_table('typing_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('words_typed', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('backspaces', sa.Integer(), nullable=True),
    sa.Column('final_wpm', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('starting_difficulty', sa.Float(), nullable=True),
    sa.Column('ending_difficulty', sa.Float(), nullable=True),
    sa.Column('avg_difficulty', sa.Float(), nullable=True),
    sa.Column('flow_score', sa.Float(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_typing_sessions_user_id'), 'typing_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keystroke_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('is_backspace', sa.Boolean(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['typing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snippet_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('snippet_id', sa.String(), nullable=True),
    sa.Column('user_wpm', sa.Float(), nullable=True),
    sa.Column('user_accuracy', sa.Float(), nullable=True),
    sa.Column('snippet_position', sa.Integer(), nullable=True),
    sa.Column('difficulty_snapshot', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['typing_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippet_usage_session_id'), 'snippet_usage', ['session_id'], unique=False)
    op.create_index(op.f('ix_snippet_usage_snippet_id'), 'snippet_usage', ['snippet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snippet_usage_snippet_id'), table_name='snippet_usage')
    op.drop_index(op.f('ix_snippet_usage_session_id'), table_name='snippet_usage')
    op.drop_table('snippet_usage')
    op.drop_table('keystroke_events')
    op.drop_table('users')
    op.drop_index(op.f('ix_typing_sessions_user_id'), table_name='typing_sessions')
    op.drop_table('typing_sessions')
    op.drop_index(op.f('ix_telemetry_snippet_raw_user_id'), table_name='telemetry_snippet_raw')
    op.drop_index(op.f('ix_telemetry_snippet_raw_snippet_id'), table_name='telemetry_snippet_raw')
    op.drop_table('telemetry_snippet_raw')
    op.drop_index('idx_difficulty', table_name='snippets')
    op.drop_table('snippets')
    # ### end Alembic commands ###
