"""add_agent_observability_models

Revision ID: 91d4c588b03b
Revises: eb70214b29f3
Create Date: 2025-12-21 09:36:40.571873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d4c588b03b'
down_revision: Union[str, Sequence[str], None] = 'eb70214b29f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_reward_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('snippet_id', sa.String(length=36), nullable=True),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('reward_accuracy', sa.Float(), nullable=True),
    sa.Column('reward_consistency', sa.Float(), nullable=True),
    sa.Column('reward_speed', sa.Float(), nullable=True),
    sa.Column('delta_accuracy', sa.Float(), nullable=True),
    sa.Column('delta_consistency', sa.Float(), nullable=True),
    sa.Column('delta_speed', sa.Float(), nullable=True),
    sa.Column('baseline_accuracy', sa.Float(), nullable=True),
    sa.Column('baseline_eff_wpm', sa.Float(), nullable=True),
    sa.Column('agent_update_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reward_created', 'agent_reward_history', ['created_at'], unique=False)
    op.create_index('idx_reward_session', 'agent_reward_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_reward_history_created_at'), 'agent_reward_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_reward_history_session_id'), 'agent_reward_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_reward_history_snippet_id'), 'agent_reward_history', ['snippet_id'], unique=False)
    op.create_index(op.f('ix_agent_reward_history_user_id'), 'agent_reward_history', ['user_id'], unique=False)
    op.create_table('agent_weight_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_count', sa.Integer(), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('mean_abs', sa.Float(), nullable=True),
    sa.Column('mean_std', sa.Float(), nullable=True),
    sa.Column('precision_mean', sa.Float(), nullable=True),
    sa.Column('precision_min', sa.Float(), nullable=True),
    sa.Column('precision_max', sa.Float(), nullable=True),
    sa.Column('avg_variance', sa.Float(), nullable=True),
    sa.Column('entropy_proxy', sa.Float(), nullable=True),
    sa.Column('weight_samples', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_created', 'agent_weight_snapshots', ['created_at'], unique=False)
    op.create_index('idx_snapshot_update_count', 'agent_weight_snapshots', ['update_count'], unique=False)
    op.create_index(op.f('ix_agent_weight_snapshots_created_at'), 'agent_weight_snapshots', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_weight_snapshots_created_at'), table_name='agent_weight_snapshots')
    op.drop_index('idx_snapshot_update_count', table_name='agent_weight_snapshots')
    op.drop_index('idx_snapshot_created', table_name='agent_weight_snapshots')
    op.drop_table('agent_weight_snapshots')
    op.drop_index(op.f('ix_agent_reward_history_user_id'), table_name='agent_reward_history')
    op.drop_index(op.f('ix_agent_reward_history_snippet_id'), table_name='agent_reward_history')
    op.drop_index(op.f('ix_agent_reward_history_session_id'), table_name='agent_reward_history')
    op.drop_index(op.f('ix_agent_reward_history_created_at'), table_name='agent_reward_history')
    op.drop_index('idx_reward_session', table_name='agent_reward_history')
    op.drop_index('idx_reward_created', table_name='agent_reward_history')
    op.drop_table('agent_reward_history')
    # ### end Alembic commands ###
