"""add normalized_features and embedding

Revision ID: ac7f5069f4ba
Revises: rewrite_snippets_v2
Create Date: 2025-12-01 04:17:41.551590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7f5069f4ba'
down_revision: Union[str, Sequence[str], None] = 'rewrite_snippets_v2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('normalized_features', sa.JSON(), nullable=True))
    op.add_column('snippets', sa.Column('embedding', sa.JSON(), nullable=True))
    op.create_index('idx_difficulty', 'snippets', ['difficulty_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_difficulty', table_name='snippets')
    op.drop_column('snippets', 'embedding')
    op.drop_column('snippets', 'normalized_features')
    # ### end Alembic commands ###
