"""Refactor user stats to JSON features

Revision ID: d03b63f3cd1f
Revises: 44abdb04cca2
Create Date: 2025-12-02 12:10:45.991395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03b63f3cd1f'
down_revision: Union[str, Sequence[str], None] = '44abdb04cca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('features', sa.JSON(), nullable=True))
    op.drop_column('users', 'best_wpm')
    op.drop_column('users', 'total_keystrokes')
    op.drop_column('users', 'overall_wpm')
    op.drop_column('users', 'total_sessions')
    op.drop_column('users', 'overall_accuracy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('overall_accuracy', sa.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('total_sessions', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('overall_wpm', sa.FLOAT(), nullable=True))
    op.add_column('users', sa.Column('total_keystrokes', sa.INTEGER(), nullable=True))
    op.add_column('users', sa.Column('best_wpm', sa.FLOAT(), nullable=True))
    op.drop_column('users', 'features')
    # ### end Alembic commands ###
